"""add fields to DocumentRecrds

Revision ID: 5c21d79f5cc9
Revises: 60dc3e9c1835
Create Date: 2026-01-17 19:22:23.796493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c21d79f5cc9'
down_revision: Union[str, None] = '60dc3e9c1835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_records', sa.Column('chunks_count', sa.Integer(), nullable=True))
    op.add_column('documents_records', sa.Column('pages_count', sa.Integer(), nullable=True))
    op.add_column('documents_records', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents_records', 'status')
    op.drop_column('documents_records', 'pages_count')
    op.drop_column('documents_records', 'chunks_count')
    # ### end Alembic commands ###
